### ISSUE TITLE
Fix list http action

### ISSUE THREAD

**Issue by shekodn** [belvo-finance/belvo-ruby#40]
## Description of the problem
**List** action creates an infinite loop when a response has pagination. 

The problem is that params is set to `nil`, as a result the request is executed in an infinite loop. This is because it never increments paging number (which should be in params)

https://github.com/belvo-finance/belvo-ruby/blob/729596254356e77ffd007c098f5b91595c6128f2/lib/belvo/http.rb#L103

#### Request
{
    "count": 101,
    "next": "https://sandbox.belvo.co/api/invoices/?page=2",
    "previous": null
}

Since it has pagination, the next request should be made to `https://sandbox.belvo.co/api/invoices/?page=2`, but since `params = nil`, the request is made to `https://sandbox.belvo.co/api/invoices/` again and since next is not null the loop goes on and on. 

## Expected impact
When this one is fixed, a user will be able to list the respective resource even though the response has pagination. 

## Proposed solution
In this story, we will fix the `list` method in `http.rb`

This is precisely how we will do it:
- Change `params = nil` for `params = Rack::Utils.parse_query URI(response.body['next']).query`

**Comment by benitocas88** [comment]
finally fixed
